openapi: 3.0.3
info:
  title: API des utilisateurs
  version: 1.0.0
paths:
  /users:
    get:
      summary: Récupérer la liste des utilisateurs
      parameters:
        - name: page
          in: query
          schema:
            type: integer
            minimum: 1
            default: 1
          required: false
          description: Numéro de la page pour la pagination
        - name: size
          in: query
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 20
          required: false
      responses:
        '200':
          description: Liste des utilisateurs
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 1
                    name:
                      type: string
                      example: Alice
                    email:
                      type: string
                      format: email
                      example: alice@example.com
        '400':
          description: Paramètres de requête invalides
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Types incorrects pour les paramètres de requête fournis