openapi: 3.0.3
info:
  title: API des produits
  version: 1.0.0
components:
  schemas:
    Product:
      type: object
      properties:
        name:
          type: string
          example: Pomme
        expiration_datetime:
          type: string
          format: date-time
          example: 2025-12-31 23:59:59
        price:
          type: number
          format: float
          example: 1.99
      required:
        - name
        - expiration_datetime
        - price
  parameters:
    Limit:
      name: limit
      in: query
      schema:
        type: integer
        minimum: 1
        default: 10
      required: false
      example: 10
    SearchQuery:
      name: q
      in: query
      schema:
        type: string
      required: false
      example: pomme
paths:
  /products:
    get:
      summary: Rechercher des produits
      parameters:
        - $ref: '#/components/parameters/Limit'
        - $ref: '#/components/parameters/SearchQuery'
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
              examples:
                multipleProducts:
                  summary: Plusieurs produits trouvés
                  value:
                    - name: Pomme
                      expiration_datetime: 2025-12-31T23:59:59Z
                      price: 1.99
                    - name: Banane
                      expiration_datetime: 2025-11-30T23:59:59Z
                      price: 0.99
                emptyList:
                  summary: Aucun produit trouvé
                  value: []